SELECT COUNT(CD_FUNCIONARIO)
FROM DB_FUNCIONARIO
WHERE DT_DESLIGAMENTO IS NULL;



SELECT NM_DEPTO, COUNT(CD_FUNCIONARIO)
FROM DB_FUNCIONARIO F 
INNER JOIN DB_DEPTO D
ON F.CD_DEPTO = D.CD_DEPTO
WHERE DT_DESLIGAMENTO IS NULL
GROUP BY NM_DEPTO;


SELECT DB_PEDIDO, COUNT(*)--, SUM(VL_TOT_PEDIDO)
FROM DB_PEDIDO;


DESC DB_FUNCIONARIO;
