CREATE TABLE PRODUTO(
COD_PRODUTO NUMBER CONSTRAINT PK_PRODUTO_COD_PRODUTO PRIMARY KEY
CONSTRAINT UK_PRODUTO_COD_PRODUTO UNIQUE,
COD_CATEGORIA NUMBER CONSTRAINT FK_COD_CATEGORIA REFERENCES CATEGORIA(COD_CATEGORIA),
PRODUTO VARCHAR(255)
);


CREATE TABLE CATEGORIA(
COD_CATEGORIA NUMBER CONSTRAINT PK_CATEGORIA_COD_CATEGORIA PRIMARY KEY
CONSTRAINT UK_CATEGORIA_COD_CATEGORIA UNIQUE,
CATEGORIA VARCHAR(255)CONSTRAINT CK_CATEGORIA_CATEGORIA CHECK (CATEGORIA IN ('DOCE', 'BEBIDA', 'CONGELADO'))
);

CREATE TABLE ITEM_PRODUTO(
COD_PRODUTO NUMBER CONSTRAINT FK_COD_PRODUTO REFERENCES PRODUTO(COD_PRODUTO),
COD_MATERIA_PRIMA NUMBER 
CONSTRAINT FK_MATERIA_PRIMA REFERENCES MATERIA_PRIMA(COD_MATERIA_PRIMA),
QUANTIDADE NUMBER CONSTRAINT NN_ITEM_PRODUTO_QUANTIDADE NOT NULL,
CONSTRAINT PK_ITEM_PRODUTO PRIMARY KEY(COD_PRODUTO, COD_MATERIA_PRIMA)
);

CREATE TABLE MATERIA_PRIMA(
COD_MATERIA_PRIMA NUMBER CONSTRAINT PK_MATERIA_PRIMA_COD_MATERIA_PRIMA PRIMARY KEY
CONSTRAINT UK_MATERIA_PRIMA_COD_MATERIA_PRIMA UNIQUE,
MATERIA_PRIMA VARCHAR(255)
);
