--não trocar = (igual) por like

SELECT NM_FUNCIONARIO, DT_CADASTRAMENTO FROM DB_FUNCIONARIO;


SELECT NM_FUNCIONARIO, VL_SALARIO_BRUTO,
VL_SALARIO_BRUTO + (VL_SALARIO_BRUTO * 0.05) AS "AUMENTO_5%",
VL_SALARIO_BRUTO + (VL_SALARIO_BRUTO * 0.08) AS "AUMENTO_8%"
FROM DB_FUNCIONARIO;

--ROUND(VALOR, QTD_CASAS_DECIMAIS) SE OMITIR O 2° AGUMENTO O NÚMERO VIRA INTEIRO
--TRUNK(VALOR, QTD_CASAS_DECIMAIS) CORTAS AS ÚLTIMAS CASAS DECIMAIS

SELECT NM_CLIENTE, QT_ESTRELAS FROM DB_CLIENTE;

SELECT DS_PRODUTO, VL_UNITARIO FROM DB_PRODUTO;

SELECT NM_CLIENTE, QT_ESTRELAS 
FROM DB_CLIENTE 
WHERE QT_ESTRELAS >= 4;

SELECT NM_CLIENTE, QT_ESTRELAS,VL_MEDIO_COMPRA
FROM DB_CLIENTE 
WHERE QT_ESTRELAS >= 3 AND VL_MEDIO_COMPRA > 100;

SELECT NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA 
FROM DB_CLIENTE 
WHERE VL_MEDIO_COMPRA > 100;

SELECT * FROM DB_PRODUTO
WHERE VL_UNITARIO > 30;


SELECT * FROM DB_PEDIDO
WHERE EXTRACT (MONTH FROM DT_PEDIDO) < 4 AND
EXTRACT (YEAR FROM DT_PEDIDO) = (SELECT MAX(EXTRACT(YEAR FROM DT_PEDIDO))
FROM DB_PEDIDO);

SELECT NM_FUNCIONARIO, DT_CADASTRAMENTO FROM DB_FUNCIONARIO
WHERE EXTRACT (MONTH FROM DT_CADASTRAMENTO) BETWEEN 11 AND 12;

SELECT * FROM DB_PEDIDO
WHERE EXTRACT (YEAR FROM DT_PEDIDO) = 2018;

